wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: xgboost
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1668896521.769965
    t:
      1:
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 23
      4: 3.9.12
      5: 0.13.5
      8:
      - 1
      - 5
    viz:
      learning_curve:
        historyFieldSettings:
          key: learning_curve
          x-axis: _step
        id: wandb/learning_curve/v1
      outlier_candidates:
        historyFieldSettings:
          key: outlier_candidates
          x-axis: _step
        id: wandb/outliers/v1
      residuals:
        historyFieldSettings:
          key: residuals
          x-axis: _step
        id: wandb/residuals_plot/v1
      summary_metrics:
        historyFieldSettings:
          key: summary_metrics
          x-axis: _step
        id: wandb/metrics/v1
